### DISCUSSION TITLE
Quiz 2: What is wrong with this Workflow?

### DISCUSSION THREAD

**Discussion by jonath92** [jonath92/ActionsFundamentals#27] [Polls]
```yaml
name: CI

on:
 workflow_dispatch:
 
jobs:
 build:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v4
  - run: gh issue create --title "Bug" --body "Please fix asap"
```
