### DISCUSSION TITLE
Quiz 1: Is this Workflow valid?

### DISCUSSION THREAD

**Discussion by jonath92** [jonath92/ActionsFundamentals#28] [Polls]
```
name: CI

on:
 workflow_dispatch:
 
jobs:
 build:
  runs-on: ubuntu-latest   
  permissions:
    issues: write
  steps:
  - uses: actions/checkout@v4
 ```

<details>
<summary>Hint</summary>
https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
</details>
