### DISCUSSION TITLE
Quiz 3 - How to reduce runs on Pull Requests?

### DISCUSSION THREAD

**Discussion by jonath92** [jonath92/ActionsFundamentals#30] [Polls]
Your Pull Request analysis workflow uses multiple code analysis tools and takes about 20 minutes to fully complete. It is triggered on pull_request event with branches filter set to main. Therefore if a developer pushes multiple commits within few minutes multiple workflows are running in parallel. How can you stop all previous workflow runs and only run the one with latest changes?

## A 

```yaml
concurrency:
 group: ${{ github.workflow }}-${{ github.ref }}
 cancel-in-progress: true
```

## B
```yaml
concurrency:
 group: ${{ github.ref }}
```

## C 
```yaml
on:
 pull_request:
   branches:
     - master
   cancel-in-progress: true
```

## D 
```yaml
on:
 pull_request:
   branches:
     - master
   types: [latest]
````
